### ISSUE TITLE
Prometheus 2.0 Format

### ISSUE THREAD

**Issue by xluffy** [xluffy/til#89]
1.x format 

```
ALERT monitor_service_down
  IF up == 0
  FOR 1m
  ANNOTATIONS {
    summary = "Node is down",
    description = "Node has been unreachable for more than 1 minutes.",
  }
```

2.0 format

```
groups:
- name: test.rules
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 1m
    annotations:
      description: Node has been unreachable for more than 1 minutes.
      summary: Node is down
```

Tool: `promtool update rules test.rules`

Ref: https://www.robustperception.io/converting-rules-to-the-prometheus-2-0-format/
