### ISSUE TITLE
Prometheus relabel, get only ip address

### ISSUE THREAD

**Issue by xluffy** [xluffy/til#92]
```
  - job_name: 'api_t_prod'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.160:9100']
        labels: {'service': 'api', 'project': 't'}
    relabel_configs:
      - source_labels: [__address__]
        regex:  '(.*):9100'
        target_label: instance
        replacement: '${1}'
```
